command_timeout = 5000
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0   = '#fbf1c7'
color_bg1   = '#3c3836'
color_blue  = '#458588'
color_aqua  = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red   = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "bold color_yellow"

[git_branch]
style = "bold color_aqua"

[git_status]
style = "bold color_red"

[git_state]
style = "bold color_red"

[username]
style_user = "bold color_orange"
style_root = "bold color_red"

[hostname]
style = "bold color_blue"

[character]
success_symbol = "[❯](bold color_green)"
error_symbol   = "[❯](bold color_red)"

[cmd_duration]
style = "bold color_yellow"

[python]
style = "bold color_blue"

[nodejs]
style = "bold color_green"

[rust]
style = "bold color_orange"
